# Generated by Django 4.2.3 on 2024-01-02 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='location',
            field=models.CharField(default='location', max_length=40),
        ),
        migrations.AddField(
            model_name='events',
            name='notes',
            field=models.CharField(default='note', max_length=200),
        ),
    ]
