# Generated by Django 4.2.3 on 2024-01-02 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_events_description_events_location_events_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='notes',
        ),
    ]
